builds:
  - main: .
    binary: chain-exporter
    ldflags: -s -w -X app/config.Version.REVISION={{.Commit}}
    goos:
      # - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*